version: '3.4'
services:
  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  trade-tracesnt-stub:
    build: ./
    ports:
      - '8085:8085'
    links:
      - 'mongodb:mongodb'
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 8080
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
