name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Test
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0
      - name: Run unit tests
        run: |
          dotnet test --project tests/TradeTracesNTStub.Test/TradeTracesNTStub.Test.csproj --filter-not-trait Category=IntegrationTests
      - name: Docker Compose Logs
        if: always()
        run: |
          docker compose logs
    ## SonarCloud
    ## Uncomment to unable SonarCloud scan
    ## Requires project to be set up in SonarCloud
    ## and the SonarCloud token to be set in the repository secrets
#   sonarcloud-scan:
#     name: CDP SonarCloud Scan
#     uses: ./.github/workflows/sonarcloud.yml
#     needs: pr-validator
#     secrets: inherit
